import React from "react";
import AppHeader from "../_comps/shared/app-header/app-header.comp";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <AppHeader type="authy" />
      {children}
    </>
  );
}
